import { getFirestore } from 'firebase-admin/firestore'
import { requireAdminUser } from '../../utils/auth'

/**
 * Initializes default library shelves.
 *
 * This endpoint seeds the Firestore database with a standard set of shelves (categories).
 * It updates existing shelves if they match the slug, preserving other data.
 *
 * @param {H3Event} event - The H3 event object.
 * @returns {Promise<{ success: boolean, message: string }>} A success message.
 * @throws {Error} Throws a 500 error if the batch commit fails.
 */
export default defineEventHandler(async (event) => {
    // Admin check logic
    await requireAdminUser(event)

    const db = getFirestore()
    const batch = db.batch()
    const shelvesRef = db.collection('shelves')

    const defaultShelves = [
        {
            title: 'Featured',
            slug: 'featured',
            description: 'Curated selections from the archivists.',
            isPublic: true,
            order: 0
        },
        {
            title: 'Original Works',
            slug: 'original',
            description: 'Canonical lore produced by the Core Branch.',
            isPublic: true,
            order: 1
        },
        {
            title: 'Community',
            slug: 'community',
            description: 'Contributions from the wider network.',
            isPublic: true,
            order: 2
        },
        {
            title: 'Public Domain',
            slug: 'public-domain',
            description: 'Works available for free use and adaptation.',
            isPublic: true,
            order: 3
        },
        {
            title: 'AI Generated',
            slug: 'ai',
            description: 'Stories generated by the Zettler AI.',
            isPublic: true,
            order: 4
        },
        {
            title: 'Unapproved',
            slug: 'unapproved',
            description: 'Submissions pending review.',
            isPublic: false,
            order: 5,
            isArchived: false
        },
        {
            title: 'Restricted',
            slug: 'restricted',
            description: 'Classified archives for admin eyes only.',
            isPublic: false,
            order: 99
        }
    ]

    for (const shelf of defaultShelves) {
        const docRef = shelvesRef.doc(shelf.slug)
        // Use set with merge to update existing or create new
        batch.set(docRef, {
            ...shelf,
            updatedAt: new Date().toISOString()
        }, { merge: true })
    }

    try {
        await batch.commit()
        return { success: true, message: 'Shelves seeded successfully' }
    } catch (e) {
        console.error("Seeding failed", e)
        throw createError({ statusCode: 500, statusMessage: 'Migration failed' })
    }
})
